### ISSUE TITLE
QR encoding is obfuscated

### ISSUE THREAD

**Issue by dolmen** [zdgeier/wifi-code#3]
https://github.com/zdgeier/wifi-code/blob/dafe07c33d83cd19a96a0701f78678a37a06aeb4/index.html#L157-L159

QR encoding is obfuscated and there is no reference to its source code. Are you really the author of this code?

**Comment by zdgeier** [comment]
fixed

**Comment by dolmen** [comment]
Performance (download latency, code size) is NOT the major issue here. Trust is the major issue.

In the current state, I can't review the code of the QR code library.

I would prefer to see the full non-obfuscated original source code (maybe in a separate .js file depending on size) and the smallest QR code encoding library.

**Comment by zdgeier** [comment]
Hi Olivier! Feel free to leave a PR of what you would like changed! I've added a comment which includes the library which I got the minified code from -- you can see the source in that link (also minified version here https://cdnjs.com/libraries/qrcode-generator). It doesn't really matter if I include the source in this repo or not since you're trusting that I haven't modified the minified JS to be something different. Even if I included the unminified JS in the file, there is still inherent risk that you take when executing someone else's code.

**Comment by zdgeier** [comment]
@dolmen keep in mind that minified does not mean obfuscated (at least in most places in webdev)! https://grantwinney.com/minification-vs-obfuscation/

**Comment by dolmen** [comment]
Source: https://github.com/kazuhikoarase/qrcode-generator/tree/master/js
